name: imdb_localization
description: This package contains localization

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  slang: ^3.25.0
  slang_flutter: ^3.25.0

dev_dependencies:
  build_runner: ^2.4.6
  slang_build_runner: ^3.25.0
  thunder_analysis:
    git:
      url: https://github.com/jakhongir16/thunder_analysis

